export const SET_TESTTRE = "SET_TESTTRE"
export const SET_INNEROBJ = "SET_INNEROBJ"
export const SET_LIST = "SET_LIST"
export const SET_LISTITEM = "SET_LISTITEM"
export const ADD_LISTITEM = "ADD_LISTITEM"
export const REMOVE_LISTITEM = "REMOVE_LISTITEM"

export default {
    SET_TESTTRE, SET_INNEROBJ, SET_LIST, SET_LISTITEM, ADD_LISTITEM, REMOVE_LISTITEM,
}